# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - dev
  - master

pool:
  vmImage: "windows-2019"

variables:
  BuildConfiguration: "Release"
  NugetPachageCachePath: 'D:\a\1\.nuget\packages'

steps:
  - task: PowerShell@2
    displayName: "Set cache directory"
    inputs:
      targetType: "inline"
      script: "[System.IO.Directory]::CreateDirectory('$(NugetPachageCachePath)')"

  - task: Cache@2
    displayName: Cache NuGet packages
    inputs:
      key: 'nuget | "$(Agent.OS)" | **/packages.lock.json,!**/bin/**'
      restoreKeys: |
        nuget | "$(Agent.OS)"
        nuget
      path: $(NugetPachageCachePath)

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: "restore"
      projects: "**/*.sln"
      feedsToUse: "select"
      vstsFeed: "/fbe17587-989e-4bd3-9e5d-9bab3ce8a196"

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: "**/*.sln"
      arguments: "--configuration $(BuildConfiguration)"

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: "**/*[Tt]est/*.csproj"
      arguments: "--configuration $(BuildConfiguration) --no-restore"
