# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - dev
  - master

pool:
  vmImage: "ubuntu-22.04"

variables:
  BuildConfiguration: "Release"

steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloud'
      organization: 'lettucebo'
      scannerMode: 'MSBuild'
      projectKey: 'Ci.Extension'
      projectName: 'Ci.Extension'

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: "restore"
      projects: "**/*.sln"

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: "**/*.sln"
      arguments: "--configuration $(BuildConfiguration)  --no-restore"

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: "**/*[Tt]est/*.csproj"
      arguments: "--configuration $(BuildConfiguration) --no-restore"

  

  - task: SonarCloudAnalyze@1

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'
